import Link from "next/link"
import Navbar from "./(layouthome)/navbar"
import Sidebar from "./(layouthome)/sidebar"
import SidebarRight from "./(layouthome)/sidebar-right"
import Footer from "./(layouthome)/footer"

export const metadata = {
    title: 'Thiết bị HQ',
    description: 'Generated by create next app',
}

export default function ClientLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <section>
            <Navbar/>
            <div className="max-w-screen-xl flex flex-row mx-auto my-4 bg-slate-100">
                <div className="basis-1/5 bg-slate-200"><Sidebar/></div>
                <div className="basis-3/5">{children}</div>
                <div className="basis-1/5"><SidebarRight/></div>
            </div>
            <Footer/>
            
        </section>
    )
}
