import Footer from "@/components/layouts/footer"
import Navbar from "@/components/layouts/navbar"

export const metadata = {
    title: 'Gio hang',
    description: 'Generated by create next app',
}

export default function CartLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <section>
            <Navbar/>
            <div className="container mx-auto bg-white w-full my-3">
                {children}
            </div>
            <Footer/>
        </section>
    )
}
