import './globals.css'

import Link from "next/link"

export const metadata = {
    title: 'Thiet Bi HQ',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    const rand = Math.floor(Math.random() * 100)
    return (
        <html lang="en">
            <body>
                <nav className="">
                    <Link href="/" >Home</Link>{" "}
                    <Link href="/login">Login</Link>{" "}
                    <Link href="/register">Register</Link>
                </nav>
                <h4>Random number {rand}</h4>
                
                {children}
            </body>
        </html>
    )
}
