import './globals.css'
import { cookies } from 'next/headers'

export const metadata = {
    title: 'Thiết bị HQ',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {

    const cookieStore = cookies()
    const theme = cookieStore.get('token')
    console.log("theme, theme", theme?.value)

    return (
        <html lang="en">
            <body className='Roboto'>
                <main>{children}</main>
            </body>
        </html>
    )
}
