import Footer from "@/components/layouts/footer"
import Navbar from "@/components/layouts/navbar"
import Sidebar from "@/components/layouts/sidebar"
import SidebarRight from "@/components/layouts/sidebar-right"
import Link from "next/link"

import Image from "next/image"
import Banner from '../../public/images/banner.jpeg'

export const metadata = {
    title: 'Thiết bị HQ',
    description: 'Generated by create next app',
}

export default function HomeLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <section>
            <Navbar/>
            <div className="container mx-auto bg-white w-full grid md:grid-cols-5">
                <div className="hidden md:block"><Sidebar/></div>
                <div className="md:col-span-4">
                    <div>
                        <Image src={Banner} alt={"Banner"} priority />
                    </div>
                    <div className="">
                        <div className="">{children}</div>
                        <div className=""><SidebarRight/></div>
                    </div>
                </div>
            </div>
            <Footer/>
        </section>
    )
}
