import Link from "next/link"
import Navbar from "./navbar"
import Sidebar from "./sidebar"

export const metadata = {
    title: 'Dashboard',
    description: 'Generated by create next app',
}

export default function DashboardLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <section>
            <Navbar/>
            <Sidebar/>
            <div className="p-4 sm:ml-64 sm:mt-14">
                {children}
            </div>
            
        </section>
    )
}
