import { verify } from "@/utils/auth/jwtSignVerify"
import Navbar from "./navbar"
import Sidebar from "./sidebar"

import { cookies } from 'next/headers'
import { accessTokenSecret } from "@/helpers/constants"

export const metadata = {
    title: 'Dashboard',
    description: 'Generated by create next app',
}

export default async function DashboardLayout({
    children,
}: {
    children: React.ReactNode
}) {

    
    return (

        <section>
            <Navbar/>
            <Sidebar/>
            <div className="p-4 sm:ml-64 sm:mt-14">
                {children}
            </div>
        </section>
    )
}
